version: "3.9"

services:
  netcheck:
    build:
      context: ..
      dockerfile: Dockerfile.netcheck
      network: host

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
    # Externen Port nur freigeben, wenn nötig:
    # ports:
    #   - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: fairment_network
    ipam:
      config:
        - subnet: 172.40.20.0/24